config/routes.rb
Rails.application.routes.draw do
  resources :arquivos
  resources :orcamentos

  root 'arquivos#new'

end

app/models/orcamento.rb
class Orcamento < ActiveRecord::Base
  has_one :arquivo
  has_many :produtos, :class_name => "OrcamentoProduto"
  has_many :servicos, :class_name => "OrcamentoServico"
end

app/controllers/orcamentos_controller.rb
class OrcamentosController < ApplicationController
  before_action :set_orcamento, only: [:show, :edit, :update, :destroy]

  # GET /orcamentos
  # GET /orcamentos.json
  def index
    @orcamentos = Orcamento.all
  end

  # GET /orcamentos/1
  # GET /orcamentos/1.json
  def show
  end

  # GET /orcamentos/new
  def new
    @orcamento = Orcamento.new
  end

  # GET /orcamentos/1/edit
  def edit
  end

  # POST /orcamentos
  # POST /orcamentos.json
  def create
    @orcamento = Orcamento.new(orcamento_params)

    respond_to do |format|
      if @orcamento.save
        format.html { redirect_to @orcamento, notice: 'Orcamento was successfully created.' }
        format.json { render :show, status: :created, location: @orcamento }
      else
        format.html { render :new }
        format.json { render json: @orcamento.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orcamentos/1
  # PATCH/PUT /orcamentos/1.json
  def update
    respond_to do |format|
      if @orcamento.update(orcamento_params)
        format.html { redirect_to @orcamento, notice: 'Orcamento was successfully updated.' }
        format.json { render :show, status: :ok, location: @orcamento }
      else
        format.html { render :edit }
        format.json { render json: @orcamento.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orcamentos/1
  # DELETE /orcamentos/1.json
  def destroy
    @orcamento.destroy
    respond_to do |format|
      format.html { redirect_to orcamentos_url, notice: 'Orcamento was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_orcamento
      @orcamento = Orcamento.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def orcamento_params
      params.require(:orcamento).permit(:numero_orcamento, :data_emissao, :data_validade, :cpf_emitente, :inscest_emitente, :nome_emitente, :endereco_emitente, :bairro_emitente, :cidade_emitente, :uf_emitente, :cep_emitente, :telefone_emitente)
    end
end

app/helpers/orcamentos_helper.rb
module OrcamentosHelper
end

app/views/orcamentos/_form.html.erb
<%= form_for(@orcamento) do |f| %>
  <% if @orcamento.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@orcamento.errors.count, "error") %> prohibited this orcamento from being saved:</h2>

      <ul>
      <% @orcamento.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :numero_orcamento %><br>
    <%= f.text_field :numero_orcamento %>
  </div>
  <div class="field">
    <%= f.label :data_emissao %><br>
    <%= f.text_field :data_emissao %>
  </div>
  <div class="field">
    <%= f.label :data_validade %><br>
    <%= f.text_field :data_validade %>
  </div>
  <div class="field">
    <%= f.label :cpf_emitente %><br>
    <%= f.text_field :cpf_emitente %>
  </div>
  <div class="field">
    <%= f.label :inscest_emitente %><br>
    <%= f.text_field :inscest_emitente %>
  </div>
  <div class="field">
    <%= f.label :nome_emitente %><br>
    <%= f.text_field :nome_emitente %>
  </div>
  <div class="field">
    <%= f.label :endereco_emitente %><br>
    <%= f.text_field :endereco_emitente %>
  </div>
  <div class="field">
    <%= f.label :bairro_emitente %><br>
    <%= f.text_field :bairro_emitente %>
  </div>
  <div class="field">
    <%= f.label :cidade_emitente %><br>
    <%= f.text_field :cidade_emitente %>
  </div>
  <div class="field">
    <%= f.label :uf_emitente %><br>
    <%= f.text_field :uf_emitente %>
  </div>
  <div class="field">
    <%= f.label :cep_emitente %><br>
    <%= f.text_field :cep_emitente %>
  </div>
  <div class="field">
    <%= f.label :telefone_emitente %><br>
    <%= f.text_field :telefone_emitente %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/orcamentos/edit.html.erb
<h1>Editing Orcamento</h1>

<%= render 'form' %>

<%= link_to 'Show', @orcamento %> |
<%= link_to 'Back', orcamentos_path %>

app/views/orcamentos/index.html.erb
<h4>Listagem Orcamentos</h4>

<table class="table">
  <thead>
    <tr>
      <th>Numero orcamento</th>
      <th>Data emissao</th>
      <th>Data validade</th>
      <th>Cpf emitente</th>
      <th>Inscest emitente</th>
      <th>Nome emitente</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @orcamentos.each do |orcamento| %>
      <tr>
        <td><%= orcamento.numero_orcamento %></td>
        <td><%= orcamento.data_emissao %></td>
        <td><%= orcamento.data_validade %></td>
        <td><%= orcamento.cpf_emitente %></td>
        <td><%= orcamento.inscest_emitente %></td>
        <td><%= orcamento.nome_emitente %></td>
        <td><%= link_to 'Show', orcamento %></td>
        <td><%= link_to 'Edit', edit_orcamento_path(orcamento) %></td>
        <td><%= link_to 'Destroy', orcamento, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Orcamento', new_orcamento_path, class: 'btn btn-success' %>

app/views/orcamentos/new.html.erb
<h1>New Orcamento</h1>

<%= render 'form' %>

<%= link_to 'Back', orcamentos_path %>

app/views/orcamentos/show.html.erb
<p id="notice"><%= notice %></p>
<h4 align="center">Orçamento</h4>
<table class ="table table-sm table-bordered"> 
	<tr>
		<td>
			<strong>Numero:</strong>
		  <%= @orcamento.numero_orcamento %>		  
		</td>
		<td>
		  <strong>Data Emissão:</strong>
		  <%= @orcamento.data_emissao %>
		</td>		
		<td colspan="5">
		  <strong>Data Validade:</strong>
		  <%= @orcamento.data_validade %>
		</td>				
	</tr>
	<tr>
		<td colspan="6" align='center'>
			EMITENTE
		<td>
	</tr>
	<tr>	
		<td>
			<strong>Cpf:</strong>
		  <%= @orcamento.cpf_emitente %>		  
		</td>
		<td>
			<strong>Inscest:</strong>
		  <%= @orcamento.inscest_emitente %>		  
		</td>
		<td>
			<strong>Telefone emitente:</strong>
		  <%= @orcamento.telefone_emitente %>		  
		</td>
		<td colspan="4">
			<strong>Nome:</strong>
		  <%= @orcamento.nome_emitente %>		  
		</td>
	</tr>
	<tr>
		<td>
			<strong>Endereco:</strong>
		  <%= @orcamento.endereco_emitente %>		  
		</td>
		<td>
			<strong>Bairro:</strong>
		  <%= @orcamento.bairro_emitente %>		  
		</td>
		<td>
			<strong>Cidade:</strong>
		  <%= @orcamento.cidade_emitente %>		  
		</td>
		<td>
		  <strong>Uf:</strong>
		  <%= @orcamento.uf_emitente %>
		</td>		
		<td colspan="3">
		  <strong>Cep:</strong>
		  <%= @orcamento.cep_emitente %>
		</td>				
	</tr>
	<tr>
		<td colspan="6" align='center'>
			CLIENTE
		<td>
	</tr>
	<tr>
		<td>
			<strong>Cliente:</strong>
		  <%= @orcamento.nome_cliente %>		  
		</td>	
		<td>
			<strong>CPF/CNPJ:</strong>
		  <%= @orcamento.cpf_cnpj_cliente %>		  
		</td>	
		<td colspan="5">
			<strong>Inscest:</strong>
		  <%= @orcamento.inscest_cliente %>		  
		</td>			
	</tr>
	<tr>
		<td>
			<strong>Email:</strong>
		  <%= @orcamento.email_cliente %>		  			
		</td>
		<td colspan="6">
			<strong>Telefone:</strong>
		  <%= @orcamento.telefone_cliente %>		  						
		</td>
	</tr>
	<tr>
		<td>
			<strong>Endereço:</strong>
		  <%= @orcamento.endereco_cliente %>		  
		</td>					
		<td>
			<strong>Bairro:</strong>
		  <%= @orcamento.bairro_cliente %>		  
		</td>	
		<td>
			<strong>Cidade:</strong>
		  <%= @orcamento.cidade_cliente %>		  
		</td>	
		<td>
			<strong>UF:</strong>
		  <%= @orcamento.uf_cliente %>		  
		</td>	
		<td colspan="5">
			<strong>CEP:</strong>
		  <%= @orcamento.cep_cliente %>		  
		</td>			
	</tr>
</table>
<h4 align='center'>Produtos</h4>
<% contador = 0%>
<table class='table table-sm table-bordered'>
	<tr>
		<th>
			Seq.
		</th>
		<th>
			Descrição
		</th>
		<th>
			Quant.
		</th>
		<th>
			Vend
		</th>
		<th>
			CF
		</th>
		<th>
			Valor Unitário
		</th>
		<th>
			Valor Total
		</th>		
	</tr>
	<% @orcamento.produtos.sorted.each do | p|%>
	<% contador = contador + 1 %>	
		<tr>
			<td>
				<%= contador%>
			</td>
			<td>
				<%= p.descricao %>
			</td>
			<td>
				<%= p.quant %>
			</td>
			<td>
				<%= p.vend_prod %>
			</td>
			<td>
				<%= p.cf %>
			</td>
			<td>
				<%= p.valor_unit%>
			</td>
			<td>
				<%= p.valor_total%>
			</td>
		</tr>
	<% end %>		
</table>
<% contador = 0 %>
<h4 align='center'>Serviços</h4>
<table class='table  table-sm table-bordered'>
	<tr>
		<th>
			Seq.
		</th>
		<th>
			Descrição
		</th>
		<th>
			Quant.			
		</th>		
		<th>
			Produtivo
		</th>
		<th>
			CF
		</th>
		<th>
			Valor Unitário
		</th>
		<th>
			Valor Total
		</th>		
	</tr>
	<% @orcamento.servicos.sorted.each do |s|%>
	<% contador = contador + 1 %>		
		<tr>
			<td>
				<%= contador %>
			</td>
			<td>
				<%= s.descricao %>								
			</td>
			<td>
				<%= s.quant %>
			</td>
			<td>
				<%= s.produtivo%>
			</td>
			<td>
				<%= s.cf %>
			</td>
			<td>
				<%= s.valor_unit%>
			</td>
			<td>
				<%= s.valor_total%>
			</td>
		</tr>
	<% end %>		
</table>

<table class ="table table-sm table-bordered"> 
	<tr>
		<td>
			<strong>Valor Total:</strong><%= @orcamento.vlr_total%>
		</td>
		<td colspan="3">
			<strong>Operação:</strong> <%= @orcamento.cod_oper %> - <%= @orcamento.desc_oper%>
		</td>		
		<tr>
			<td>
				<strong>Vendedor:</strong> <%= @orcamento.cod_vendedor%> - <%= @orcamento.nome_vendedor%>
			</td>
			<td colspan="3">
				<strong>Departamento:</strong> <%= @orcamento.cod_departamento%> - <%= @orcamento.nome_departamento%>
			</td>			
		</tr>
		<tr>
			<td>
				<strong>Placa:</strong> <%= @orcamento.placa%>
			</td>
			<td>
				<strong>Chassi:</strong> <%= @orcamento.chassi%>
			</td>
			<td>
				<strong>Ano/Modelo:</strong> <%= @orcamento.ano_modelo%>
			</td>			
			<td>
				<strong>KMs Rodados:</strong> <%= @orcamento.km_rodado%>
			</td>			
		</tr>
		<tr>
			<td>
				<strong>Público:</strong> <%= @orcamento.cod_publico%> - <%= @orcamento.nome_publico%>
			</td>
			<td colspan="3">
				<strong>Forma de Pagamento:</strong> <%= @orcamento.cod_pagamento%> - <%= @orcamento.desc_pagamento %>
			</td>
		</tr>
		
</table>

<br>
<%= link_to 'Nova Importação', new_arquivo_path, class: "btn btn-success" %>
<br><br>